[package]
name = "sdust-hir"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
la-arena.workspace = true
sdust-syntax = { path = "../sdust-syntax" }
sdust-ast = { path = "../sdust-ast" }
sdust-diagnostics = { path = "../sdust-diagnostics" }

[dev-dependencies]
insta.workspace = true
