[workspace]
resolver = "2"
members = [
    "crates/sdust-syntax",
    "crates/sdust-ast",
    "crates/sdust-diagnostics",
    "crates/sdust-hir",
    "crates/sdust-types",
    "crates/sdust-borrow",
    "crates/sdust-sir",
    "crates/sdust-runtime",
    "crates/sdust-codegen-cranelift",
    "crates/sdust-codegen-wasm",
    "crates/sdust-codegen-llvm",
    "crates/sdust-fmt",
    "crates/sdust-lsp",
    "crates/sdust-pkg",
    "crates/sdust-doc",
    "crates/sdust-stdlib",
    "crates/sdust-debuginfo",
    "crates/sdust-driver",
    "crates/sdust-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.85"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/hassard0/stardust"
authors = ["Ian Hassard <ihassard@gmail.com>"]

[workspace.dependencies]
logos = "0.14"
rowan = "0.15"
la-arena = "0.3"
ariadne = "0.4"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
toml = "0.8"
thiserror = "1"
insta = { version = "1", features = ["yaml"] }
tokio = { version = "1", features = ["rt-multi-thread", "rt", "macros", "time", "net", "io-util", "sync", "fs"] }
parking_lot = "0.12"
dashmap = "5"
cranelift-codegen = "0.132"
cranelift-frontend = "0.132"
cranelift-module = "0.132"
cranelift-jit = "0.132"
cranelift-object = "0.132"
cranelift-native = "0.132"
target-lexicon = "0.13"
wasm-encoder = "0.250"
wasmparser = "0.250"
bumpalo = "3"
libloading = "0.9"
tower-lsp = "0.20"
lsp-types = "0.97"
sha2 = "0.10"
hex = "0.4"
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls", "blocking"] }
git2 = { version = "0.19", default-features = false }
pulldown-cmark = "0.12"
askama = "0.12"
inkwell = { version = "0.5", features = ["llvm17-0"] }
wit-component = "0.225"
wit-parser = "0.225"
gimli = "0.31"
object = { version = "0.36", features = ["read", "write"] }
serde_json = "1"
rustls = { version = "0.23", default-features = false, features = ["std", "tls12"] }
rustls-pemfile = "2"
tokio-rustls = "0.26"
hyper = { version = "1", features = ["full"] }
hyper-util = { version = "0.1", features = ["full"] }
http-body-util = "0.1"
opentelemetry = "0.27"
opentelemetry-otlp = { version = "0.27", features = ["grpc-tonic", "http-proto"] }
opentelemetry_sdk = { version = "0.27", features = ["rt-tokio"] }
tokio-util = "0.7"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
