[package]
name = "mty-types-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[workspace]

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.mty-types]
path = ".."

[dependencies.mty-driver]
path = "../../mty-driver"

[dependencies.mty-syntax]
path = "../../mty-syntax"

[[bin]]
name = "typeck_fuzz"
path = "fuzz_targets/typeck_fuzz.rs"
test = false
doc = false
bench = false
