[package]
name = "mty-debuginfo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Mighty debug-info builder: DWARF for native objects, source-map v3 for Wasm."

[dependencies]
gimli = { workspace = true, features = ["read", "write", "std"] }
object = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
gimli = { workspace = true, features = ["read", "write", "std"] }

[lints]
workspace = true
