[package]
name = "mty-doc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
mty-syntax = { path = "../mty-syntax" }
mty-ast = { path = "../mty-ast" }
mty-hir = { path = "../mty-hir" }
mty-types = { path = "../mty-types" }
mty-fmt = { path = "../mty-fmt" }
mty-diagnostics = { path = "../mty-diagnostics" }
pulldown-cmark.workspace = true
askama.workspace = true
rowan.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile = "3"

[lints]
workspace = true
