[package]
name = "sdust-doc"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
sdust-syntax = { path = "../sdust-syntax" }
sdust-ast = { path = "../sdust-ast" }
sdust-hir = { path = "../sdust-hir" }
sdust-types = { path = "../sdust-types" }
sdust-fmt = { path = "../sdust-fmt" }
sdust-diagnostics = { path = "../sdust-diagnostics" }
pulldown-cmark.workspace = true
askama.workspace = true
rowan.workspace = true

[dev-dependencies]
insta.workspace = true
tempfile = "3"
