[package]
name = "sdust-fmt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
rowan.workspace = true
sdust-syntax = { path = "../sdust-syntax" }

[dev-dependencies]
insta.workspace = true
