[package]
name = "sdust-borrow"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
sdust-hir = { path = "../sdust-hir" }
sdust-types = { path = "../sdust-types" }
sdust-diagnostics = { path = "../sdust-diagnostics" }

[dev-dependencies]
sdust-syntax = { path = "../sdust-syntax" }
sdust-ast = { path = "../sdust-ast" }
sdust-driver = { path = "../sdust-driver" }
