[package]
name = "sdust-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
sdust-syntax = { path = "../sdust-syntax" }
sdust-ast = { path = "../sdust-ast" }

[dev-dependencies]
sdust-syntax = { path = "../sdust-syntax" }
