//! WIT (Wasm Interface Type) generation for Mighty packages.
//!
//! Given a `mty_ir::Program` + a [`WasmTarget`], we emit a small
//! `.wit` document that describes the package's *public* surface:
//!
//! - top-level fns become `func` members of the package's main
//!   interface (`stardust:pkg/lib`),
//! - `struct` ADTs become `record` types,
//! - `enum` ADTs become `variant` types (or plain `enum` when none
//!   of the variants carry payloads),
//! - capability families (Fs, Net, …) referenced anywhere in the
//!   program become component imports under `mty:caps/<family>`,
//! - the host-provided `log` builtin is wired to `wasi:cli/print`
//!   for `wasm32-wasi` and to `mty:web/log` for `wasm32-web`.
//!
//! After we construct the textual WIT we feed it through
//! `wit_parser::Resolve::push_str` for round-trip validation; any
//! parse failure surfaces as [`WasmError::Invalid`].
//!
//! ### Why this shape?
//!
//! The Component Model has no first-class concept of an "effect" so
//! Mighty effects are *not* exposed in WIT today; they show up as
//! a comment block at the top of the document (`// effects: Net, …`)
//! that downstream tooling can pick up. This is documented in
//! `docs/internals/codegen-wasm.md` and in WASM_CM_V0_2_NOTES.md at
//! the repo root.

use crate::error::{CompileResult, WasmError};
use crate::target::WasmTarget;
use mty_ir::ir::{AdtRef, AdtRefKind, FieldRef, Function, IrTy, Program, VariantRef};
use mty_types::{FloatKind, IntKind};
use std::collections::BTreeSet;
use std::fmt::Write as _;

/// The generated WIT document plus enough metadata for the rest of
/// the backend to embed it back into a component.
#[derive(Debug, Clone)]
pub struct WitDocument {
    /// Canonical textual WIT (validated round-trip).
    pub text: String,
    /// Package id we use — derived from `pkg_name`.
    pub package_id: String,
    /// World name (always `<pkg>-world`).
    pub world_name: String,
    /// Source target the doc was emitted for.
    pub target: WasmTarget,
}

impl WitDocument {
    /// Re-parse `text` with `wit_parser::Resolve` and return the
    /// `(PackageId, WorldId)` selection used by `wit-component`.
    pub fn resolve(
        &self,
    ) -> Result<
        (
            wit_parser::Resolve,
            wit_parser::PackageId,
            wit_parser::WorldId,
        ),
        WasmError,
    > {
        let mut resolve = wit_parser::Resolve::default();
        let pkg = resolve
            .push_str("stardust.wit", &self.text)
            .map_err(|e| WasmError::Invalid(format!("wit re-parse: {e:#}")))?;
        let world = resolve
            .select_world(pkg, Some(&self.world_name))
            .map_err(|e| WasmError::Invalid(format!("wit world select: {e:#}")))?;
        Ok((resolve, pkg, world))
    }
}

/// Emit a WIT document for `prog`. `pkg_name` is the kebab-case
/// package name (the source-file stem); it becomes the second half
/// of the `stardust:<pkg>` package id.
pub fn emit_wit(prog: &Program, pkg_name: &str, target: WasmTarget) -> CompileResult<WitDocument> {
    let pkg_id = sanitize_pkg_id(pkg_name);
    let world_name = format!("{}-world", pkg_id);

    // Pre-collect program shape.
    let exported_fns: Vec<&Function> = prog.fns.iter().filter(|f| is_exportable_fn(f)).collect();
    let exported_adts: Vec<&AdtRef> = prog.adts.iter().filter(|a| is_exportable_adt(a)).collect();
    let caps = collect_cap_families(prog);
    let effects = collect_effects_comment(prog);

    // Build the user-package body (top-level semicolon syntax —
    // exactly one top-level `package X:Y;` is required by
    // `UnresolvedPackageGroup::parse`). Stub host packages are
    // emitted in nested form alongside.
    let mut user_body = String::new();
    writeln!(user_body, "// AUTO-GENERATED by mty-codegen-wasm.").unwrap();
    writeln!(
        user_body,
        "// Source target: {} — Component Model output.",
        target.triple()
    )
    .unwrap();
    writeln!(user_body, "package stardust:{};", pkg_id).unwrap();
    writeln!(user_body).unwrap();

    // World — declares imports and inline exports. Inline exports
    // (vs `export <iface>;`) keep the canonical core-wasm export
    // names simple (e.g. `main`, `add`) which is what the
    // slice-8 lowerer already emits. Types are emitted inside the
    // world as well.
    writeln!(user_body, "world {} {{", world_name).unwrap();
    let log_iface = match target {
        WasmTarget::Wasi => "wasi:cli/log",
        WasmTarget::Web => "mty:web/log",
    };
    writeln!(user_body, "  import {};", log_iface).unwrap();
    // v0.5 dogfood Gap-2 — web target also imports the real DOM
    // interface so user code can call `dom.set_text`, `dom.get_text`,
    // `dom.on_click`, `dom.query`. The companion JS shim
    // (`demos/02_counter_web/web/dom-shim.js`) implements the imports
    // against `document.*`.
    if matches!(target, WasmTarget::Web) {
        writeln!(user_body, "  import mty:web/dom;").unwrap();
    }
    for cap in &caps {
        writeln!(user_body, "  import mty:caps/{};", cap).unwrap();
    }
    for adt in &exported_adts {
        emit_adt(&mut user_body, adt)?;
    }
    if !exported_adts.is_empty() && !exported_fns.is_empty() {
        writeln!(user_body).unwrap();
    }
    for f in &exported_fns {
        emit_world_export_fn(&mut user_body, f)?;
    }
    if let Some(eff) = effects {
        writeln!(user_body, "  // effects: {}", eff).unwrap();
    }
    writeln!(user_body, "}}").unwrap();
    writeln!(user_body).unwrap();

    // Append host stubs (nested-package syntax — they're not the
    // main package, just satisfy import resolution).
    append_host_stubs(&mut user_body, target);

    // Round-trip validation.
    let with_stubs = user_body;
    let mut resolve = wit_parser::Resolve::default();
    let _ = resolve
        .push_str("stardust.wit", &with_stubs)
        .map_err(|e| WasmError::Invalid(format!("wit round-trip: {e:#}")))?;

    Ok(WitDocument {
        text: with_stubs,
        package_id: format!("stardust:{}", pkg_id),
        world_name,
        target,
    })
}

/// Append host-package stubs (in nested-package syntax) so
/// `wit_parser::Resolve` is satisfied without needing the actual
/// `wasi:cli` / `mty:web` packages on disk.
fn append_host_stubs(out: &mut String, target: WasmTarget) {
    // mty:caps stub — covers every capability family the
    // backend currently knows about.
    out.push_str("package mty:caps {\n");
    out.push_str("  interface fs {\n");
    out.push_str("    read: func(path: string) -> result<list<u8>, string>;\n");
    out.push_str("    write: func(path: string, data: list<u8>) -> result<_, string>;\n");
    out.push_str("  }\n");
    out.push_str("  interface net {\n");
    out.push_str("    get: func(url: string) -> result<list<u8>, string>;\n");
    out.push_str("  }\n");
    out.push_str("  interface clock {\n");
    out.push_str("    now-millis: func() -> u64;\n");
    out.push_str("  }\n");
    out.push_str("  interface dom {\n");
    out.push_str("    get-element-by-id: func(id: string) -> option<u32>;\n");
    out.push_str("  }\n");
    out.push_str("  interface model {\n");
    out.push_str("    invoke: func(prompt: string) -> result<string, string>;\n");
    out.push_str("  }\n");
    out.push_str("}\n\n");

    match target {
        WasmTarget::Wasi => {
            out.push_str("package wasi:cli {\n");
            out.push_str("  interface log {\n");
            out.push_str("    log: func(msg: string);\n");
            out.push_str("  }\n");
            out.push_str("}\n");
        }
        WasmTarget::Web => {
            out.push_str("package mty:web {\n");
            out.push_str("  interface log {\n");
            out.push_str("    log: func(msg: string);\n");
            out.push_str("  }\n");
            // v0.5 dogfood Gap-2: expanded DOM surface. The JS shim
            // (`demos/02_counter_web/web/dom-shim.js`) implements each
            // of these against `document.*` so Mighty code can drive
            // the page directly instead of parsing log lines.
            out.push_str("  interface dom {\n");
            out.push_str("    set-text: func(id: string, text: string);\n");
            // v0.5 NOTE: `get-text` and `query` return `u32` handles into
            // the JS shim's string table rather than `string`. The core
            // module imports these as `(ptr,len) -> i32`, and the WIT
            // canonical-ABI lift for `-> string` would expect a
            // `(ptr,len,retptr) -> ()` shape. Keeping `u32` here keeps
            // the WIT and core import signatures aligned. v0.6 will
            // switch back to `string` once the canonical-ABI return-area
            // bridge is wired in `emit.rs`.
            out.push_str("    get-text: func(id: string) -> u32;\n");
            out.push_str("    on-click: func(id: string, callback-tag: string);\n");
            out.push_str("    query: func(selector: string) -> u32;\n");
            out.push_str("    // legacy v0.4 ops, kept for back-compat with the\n");
            out.push_str("    // existing JS host wrapper.\n");
            out.push_str("    get-element-by-id: func(id: string) -> option<u32>;\n");
            out.push_str("    set-text-handle: func(handle: u32, text: string);\n");
            out.push_str("  }\n");
            out.push_str("}\n");
        }
    }
}

fn sanitize_pkg_id(name: &str) -> String {
    let mut s = String::with_capacity(name.len());
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            s.push(c.to_ascii_lowercase());
        } else if c == '-' || c == '_' {
            s.push('-');
        }
    }
    if s.is_empty() || !s.chars().next().unwrap().is_ascii_alphabetic() {
        s.insert(0, 'p');
    }
    s
}

/// A fn is "exportable" if its name doesn't start with `_` (Mighty
/// convention for "private") and its signature is round-trippable
/// through WIT (i.e. its params and return type all map to a WIT
/// type).
fn is_exportable_fn(f: &Function) -> bool {
    if f.name.starts_with('_') || f.name.contains("::") {
        return false;
    }
    if wit_ty(&f.ret_ty).is_none() && !matches!(f.ret_ty, IrTy::Unit | IrTy::Never) {
        return false;
    }
    for p in &f.params {
        let ty = &f.locals[p.0 as usize].ty;
        if wit_ty(ty).is_none() && !matches!(ty, IrTy::Unit | IrTy::Never) {
            return false;
        }
    }
    true
}

fn is_exportable_adt(a: &AdtRef) -> bool {
    if a.name.starts_with('_') {
        return false;
    }
    if matches!(a.kind, AdtRefKind::Opaque) {
        return false;
    }
    match a.kind {
        AdtRefKind::Struct => a
            .variants
            .first()
            .map(|v| v.fields.iter().all(|f| wit_ty(&f.ty).is_some()))
            .unwrap_or(false),
        AdtRefKind::Enum => a
            .variants
            .iter()
            .all(|v| v.fields.iter().all(|f| wit_ty(&f.ty).is_some())),
        AdtRefKind::Opaque => false,
    }
}

fn emit_world_export_fn(out: &mut String, f: &Function) -> CompileResult<()> {
    let name = kebab(&f.name);
    write!(out, "  export {}: func(", name).unwrap();
    write_fn_signature_tail(out, f)
}

fn write_fn_signature_tail(out: &mut String, f: &Function) -> CompileResult<()> {
    let mut first = true;
    for p in &f.params {
        let decl = &f.locals[p.0 as usize];
        if matches!(decl.ty, IrTy::Unit | IrTy::Never) {
            continue;
        }
        let Some(w) = wit_ty(&decl.ty) else {
            return Err(WasmError::Invalid(format!(
                "wit: cannot lower fn param type {:?}",
                decl.ty
            )));
        };
        if !first {
            write!(out, ", ").unwrap();
        }
        first = false;
        write!(out, "{}: {}", kebab(&decl.name), w).unwrap();
    }
    write!(out, ")").unwrap();
    if !matches!(f.ret_ty, IrTy::Unit | IrTy::Never) {
        let Some(rt) = wit_ty(&f.ret_ty) else {
            return Err(WasmError::Invalid(format!(
                "wit: cannot lower fn return type {:?}",
                f.ret_ty
            )));
        };
        write!(out, " -> {}", rt).unwrap();
    }
    writeln!(out, ";").unwrap();
    Ok(())
}

fn emit_adt(out: &mut String, a: &AdtRef) -> CompileResult<()> {
    let name = kebab(&a.name);
    match a.kind {
        AdtRefKind::Struct => {
            let v0 = a
                .variants
                .first()
                .ok_or_else(|| WasmError::Invalid(format!("struct {} has no variant", a.name)))?;
            writeln!(out, "  record {} {{", name).unwrap();
            for (i, f) in v0.fields.iter().enumerate() {
                emit_field(out, f, i)?;
            }
            writeln!(out, "  }}").unwrap();
        }
        AdtRefKind::Enum => {
            let payload_free = a.variants.iter().all(|v| v.fields.is_empty());
            if payload_free {
                write!(out, "  enum {} {{ ", name).unwrap();
                let mut first = true;
                for v in &a.variants {
                    if !first {
                        write!(out, ", ").unwrap();
                    }
                    first = false;
                    write!(out, "{}", kebab(&v.name)).unwrap();
                }
                writeln!(out, " }}").unwrap();
            } else {
                writeln!(out, "  variant {} {{", name).unwrap();
                for v in &a.variants {
                    emit_variant_arm(out, v)?;
                }
                writeln!(out, "  }}").unwrap();
            }
        }
        AdtRefKind::Opaque => {}
    }
    Ok(())
}

fn emit_field(out: &mut String, f: &FieldRef, idx: usize) -> CompileResult<()> {
    let name = match &f.name {
        Some(n) => kebab(n),
        None => format!("f{idx}"),
    };
    let Some(w) = wit_ty(&f.ty) else {
        return Err(WasmError::Invalid(format!(
            "wit: cannot lower field type {:?}",
            f.ty
        )));
    };
    writeln!(out, "    {}: {},", name, w).unwrap();
    Ok(())
}

fn emit_variant_arm(out: &mut String, v: &VariantRef) -> CompileResult<()> {
    let name = kebab(&v.name);
    if v.fields.is_empty() {
        writeln!(out, "    {},", name).unwrap();
    } else if v.fields.len() == 1 {
        let Some(w) = wit_ty(&v.fields[0].ty) else {
            return Err(WasmError::Invalid(format!(
                "wit: cannot lower variant payload {:?}",
                v.fields[0].ty
            )));
        };
        writeln!(out, "    {}({}),", name, w).unwrap();
    } else {
        // Multi-field variant: wrap into a tuple.
        let mut parts = Vec::with_capacity(v.fields.len());
        for fld in &v.fields {
            let Some(w) = wit_ty(&fld.ty) else {
                return Err(WasmError::Invalid(format!(
                    "wit: cannot lower variant payload {:?}",
                    fld.ty
                )));
            };
            parts.push(w);
        }
        writeln!(out, "    {}(tuple<{}>),", name, parts.join(", ")).unwrap();
    }
    Ok(())
}

/// Convert a SIR type to a WIT type string. Returns `None` for
/// shapes that can't be expressed in WIT (e.g. raw pointers).
fn wit_ty(t: &IrTy) -> Option<String> {
    Some(match t {
        IrTy::Bool => "bool".into(),
        IrTy::Char => "char".into(),
        IrTy::Str | IrTy::String => "string".into(),
        IrTy::Bytes => "list<u8>".into(),
        IrTy::Int(k) => match k {
            IntKind::I8 => "s8".into(),
            IntKind::U8 => "u8".into(),
            IntKind::I16 => "s16".into(),
            IntKind::U16 => "u16".into(),
            IntKind::I32 | IntKind::IntInfer => "s32".into(),
            IntKind::U32 => "u32".into(),
            IntKind::I64 | IntKind::ISize => "s64".into(),
            IntKind::U64 | IntKind::USize => "u64".into(),
            IntKind::I128 | IntKind::U128 => return None,
        },
        IrTy::Float(k) => match k {
            FloatKind::F32 => "f32".into(),
            FloatKind::F64 | FloatKind::FloatInfer => "f64".into(),
        },
        IrTy::Duration | IrTy::Size => "u64".into(),
        IrTy::Array { elem, .. } => format!("list<{}>", wit_ty(elem)?),
        IrTy::Tuple(parts) => {
            if parts.is_empty() {
                return None;
            }
            let mut bits = Vec::with_capacity(parts.len());
            for p in parts {
                bits.push(wit_ty(p)?);
            }
            format!("tuple<{}>", bits.join(", "))
        }
        IrTy::Ref { inner, .. } => wit_ty(inner)?,
        IrTy::Adt(_, _) => return None, // resolved by name elsewhere
        IrTy::Cap { .. }
        | IrTy::Dyn(_)
        | IrTy::RawPtr(_)
        | IrTy::Fn { .. }
        | IrTy::Module(_)
        | IrTy::Param(_)
        | IrTy::Unit
        | IrTy::Never
        | IrTy::Error => return None,
    })
}

/// Convert a snake_case / camelCase identifier into WIT's required
/// kebab-case (lowercase, hyphen-separated).
fn kebab(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    let mut prev_was_lower = false;
    for c in s.chars() {
        if c == '_' || c == ' ' {
            if !out.ends_with('-') {
                out.push('-');
            }
            prev_was_lower = false;
        } else if c.is_ascii_uppercase() {
            if prev_was_lower && !out.ends_with('-') {
                out.push('-');
            }
            out.push(c.to_ascii_lowercase());
            prev_was_lower = false;
        } else if c.is_ascii_alphanumeric() {
            out.push(c);
            prev_was_lower = c.is_ascii_lowercase();
        } else {
            // skip unicode / punctuation for v0.2
        }
    }
    let trimmed = out.trim_matches('-').to_string();
    if trimmed.is_empty() {
        return "x".into();
    }
    // WIT identifiers can't start with a digit.
    if trimmed.chars().next().unwrap().is_ascii_digit() {
        format!("x{trimmed}")
    } else {
        trimmed
    }
}

fn collect_cap_families(prog: &Program) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    for f in &prog.fns {
        for l in &f.locals {
            if let IrTy::Cap { family, .. } = &l.ty {
                out.insert(format!("{family:?}").to_ascii_lowercase());
            }
        }
    }
    out
}

fn collect_effects_comment(prog: &Program) -> Option<String> {
    let mut set = BTreeSet::new();
    for f in &prog.fns {
        for e in &f.effects {
            set.insert(format!("{e:?}"));
        }
    }
    if set.is_empty() {
        None
    } else {
        Some(set.into_iter().collect::<Vec<_>>().join(", "))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use mty_hir::SourceSpan;
    use mty_ir::ir::{
        Block, BlockId, Const, Function, IrFnId, LocalDecl, LocalSource, Operand, Program, Term,
    };

    fn empty_main() -> Program {
        let mut p = Program::default();
        p.fns.push(Function {
            id: IrFnId(0),
            name: "main".into(),
            params: vec![],
            locals: vec![LocalDecl {
                name: "_0".into(),
                ty: IrTy::Unit,
                mutable: false,
                source: LocalSource::Return,
            }],
            blocks: vec![Block {
                id: BlockId(0),
                stmts: vec![],
                terminator: Term::Return(Operand::Const(Const::Unit)),
            }],
            entry: BlockId(0),
            ret_ty: IrTy::Unit,
            effects: vec![],
            hir_fn: None,
            span: SourceSpan { start: 0, end: 0 },
        });
        p
    }

    #[test]
    fn emit_wit_round_trips_empty_main() {
        let p = empty_main();
        let doc = emit_wit(&p, "hello", WasmTarget::Wasi).expect("emit");
        // Must contain main fn export.
        assert!(
            doc.text.contains("export main: func()"),
            "wit was: {}",
            doc.text
        );
        // Re-parse via resolve.
        let (_resolve, _pkg, _world) = doc.resolve().expect("resolve roundtrip");
    }

    #[test]
    fn kebab_works() {
        assert_eq!(kebab("snake_case"), "snake-case");
        assert_eq!(kebab("camelCase"), "camel-case");
        assert_eq!(kebab("HTTPServer"), "httpserver");
        assert_eq!(kebab("_leading"), "leading");
        assert_eq!(kebab("42x"), "x42x");
    }

    #[test]
    fn wit_ty_scalars() {
        assert_eq!(wit_ty(&IrTy::Bool).as_deref(), Some("bool"));
        assert_eq!(wit_ty(&IrTy::String).as_deref(), Some("string"));
        assert_eq!(wit_ty(&IrTy::Int(IntKind::U32)).as_deref(), Some("u32"));
    }

    #[test]
    fn web_target_uses_stardust_web_log() {
        let doc = emit_wit(&empty_main(), "hello", WasmTarget::Web).expect("emit");
        assert!(
            doc.text.contains("import mty:web/log"),
            "wit was: {}",
            doc.text
        );
    }

    #[test]
    fn wasi_target_uses_wasi_cli_log() {
        let doc = emit_wit(&empty_main(), "hello", WasmTarget::Wasi).expect("emit");
        assert!(
            doc.text.contains("import wasi:cli/log"),
            "wit was: {}",
            doc.text
        );
    }
}
