[package]
name = "mailbox-throughput-rust-tokio"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "sync"] }

[[bin]]
name = "mailbox-throughput-rust-tokio"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
