[package]
name = "sdust-codegen-wasm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Stardust Wasm core-module codegen backend — slice 8."

[dependencies]
sdust-sir = { path = "../sdust-sir" }
sdust-types = { path = "../sdust-types" }
sdust-hir = { path = "../sdust-hir" }
sdust-diagnostics = { path = "../sdust-diagnostics" }
wasm-encoder = { workspace = true }
wasmparser = { workspace = true }
thiserror = { workspace = true }
